name: 🔄 Versioning & Deployment

env:
  DOCKERHUB_USER: "cuembybot"
  REPO_DEVOPS: "willmendezcuemby/ccp-devops"
  REPO_GITOPS: "willmendezcuemby/gitops-ccp"
  GITOPS_FILE_PATH: "overlays/ccp-controlplane-service/version_info.json"
  ORG_NAME: 'cuemby'
  METADATA_PATH: 'overlays/ccp-controlplane-service/version_info.json'
  DEPLOYMENT_PATCH_PATH: 'overlays/ccp-controlplane-service/dev'
  DISPATCH_COMMIT_MSG: 'Manual Dispatch to test the versioning action'
  DOCKER_FILE_PATH: './Dockerfile'

on:
  workflow_dispatch:
    inputs:
      sourceBranch:
        description: 'Source branch'
        required: true
        default: 'feature-branch'
      targetBranch:
        description: 'Target branch'
        required: true
        default: 'main'
      

jobs:
  versioning_job:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.versioning_step.outputs.success }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout devops repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_DEVOPS }}
          token: ${{ secrets.DEVOPS_TOKEN }}
          path: devops_repo
      
      - name: Versioning step
        uses: ./devops_repo/.github/actions/semver-management
        with:
          GH_TOKEN: ${{ secrets.DEVOPS_TOKEN }}
          EXTERNAL_REPO: ${{ env.REPO_GITOPS }}
          EXTERNAL_REPO_FILE_PATH: ${{ env.GITOPS_FILE_PATH }}
          SOURCE_BRANCH: ${{ github.event.inputs.sourceBranch }}
          TARGET_BRANCH: ${{ github.event.inputs.targetBranch }}
          COMMIT_MESSAGE: ${{ env.DISPATCH_COMMIT_MSG }}

  deploy_job:
    needs: versioning_job
    if: needs.versioning_job.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout devops repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_DEVOPS }}
          token: ${{ secrets.DEVOPS_TOKEN }}
          path: devops_repo
          
      - name: Clone "cuemby/ccp-sdk" submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/ccp-sdk.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: ccp-sdk

      - name: Clone "cuemby/by-go-utils" submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/by-go-utils.git
          ref: "dev-1"
          token: ${{ secrets.GH_TOKEN }}
          path: by-go-utils

      - name: clone submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/ccp-event-client.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: ccp-event-client

      - name: clone submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/by-email-notification-sdk.git
          ref: "master"
          token: ${{ secrets.GH_TOKEN }}
          path: by-email-notification-sdk

      - name: clone submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/ccp-services-byreports.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: ccp-services-byreports

      - name: Clone "cuemby/ccp-notifications-service" submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/ccp-notifications-service.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: ccp-notifications-service

      - name: Clone "cuemby/ccp-blockchain-operator" submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/ccp-blockchain-operator.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: ccp-blockchain-operator

      - name: Clone "cuemby/cap-cloud-providers-service" submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/cap-cloud-providers-service.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: cap-cloud-providers-service

      - name: Clone "cuemby/cap-policy-service" submodule
        uses: actions/checkout@v3
        with:
          repository: cuemby/cap-policy-service.git
          ref: "dev"
          token: ${{ secrets.GH_TOKEN }}
          path: cap-policy-service

      - name: temp modify go.mod
        run: |
          echo "replace github.com/cuemby/ccp-sdk  => ./ccp-sdk" >> go.mod
          echo "replace github.com/cuemby/by-go-utils  => ./by-go-utils" >> go.mod
          echo "replace github.com/cuemby/ccp-event-client  => ./ccp-event-client" >> go.mod
          echo "replace github.com/cuemby/by-email-notification-sdk  => ./by-email-notification-sdk" >> go.mod
          echo "replace github.com/cuemby/ccp-services-byreports  => ./ccp-services-byreports" >> go.mod
          echo "replace github.com/cuemby/ccp-notifications-service  => ./ccp-notifications-service" >> go.mod
          echo "replace github.com/cuemby/ccp-blockchain-operator  => ./ccp-blockchain-operator" >> go.mod
          echo "replace github.com/cuemby/cap-cloud-providers-service  => ./cap-cloud-providers-service" >> go.mod
          echo "replace github.com/cuemby/cap-policy-service  => ./cap-policy-service" >> go.mod
          echo "doneccp-sdk"


      - name: Deploy to Docker and Update Kustomize
        uses: ./devops_repo/.github/actions/version-upgrade-action
        with:
          gh_token: ${{ secrets.DEVOPS_TOKEN }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub_username: ${{ env.DOCKERHUB_USER }}
          organization_name: ${{ env.ORG_NAME }}
          external_repo: ${{ env.REPO_GITOPS }}
          metadata_path: ${{ env.METADATA_PATH }}
          deployment_overlay_path: ${{ env.DEPLOYMENT_PATCH_PATH }}
          gh_repo_name: ${{ github.event.repository.name }}
          release_branch_docker_alias: ${{ github.event.inputs.targetBranch }}
          dockerfile_path:  ${{ env.DOCKER_FILE_PATH }}

    
